nome = str(input("Digite seu nome completo: ")).strip()
dividido = nome.split()
print("Nome com todas letras maiusculas: {}".format(nome.upper()))
print("Nome com todas letras minusculas: {}".format(nome.lower()))
print("Quantas letras tem ao todo {} letras".format(len(nome.replace(" ", ""))))
print("Seu primeiro nome é {} e tem {} letras".format(dividido[0], len(dividido[0])))
